# Parameter file for rg-2018-03-09_cerebellum.py
#
data:
  x0: 0
  x1: 12320
  y0: 0
  y1: 12320
  z0: 0
  z1: 3072
  tile-size: 2560
  ratio: 1

aff:
  mx: 160
  my: 160
  mz: 8

  vx: 1540
  vy: 1540
  vz: 192

  px: 80
  py: 80
  pz: 4

zwatershed:
  find-basins:
    a-low: .05
    a-high: .8
    a-rel: 0
  aggregate:
    s-dust: 150
    s-thres: 150
    s-dust-merge: .2
    s-mst-merge: .5
  chunkZ: 180

waterz:
    mf: "aff85_his256"
    thres: "0.5"
    chunkZ: 90

files:
    result-path: "/n/coxfs01/donglai/jwr/20um_20180720/"
