# All other configurations are set by default. If you want to change them,
# please modify ../connectomics/config/config.py
SYSTEM:
  NUM_GPUS: 4
  NUM_CPUS: 4
MODEL:
  ARCHITECTURE: 'unet_residual_3d'
  BATCH_SIZE: 32
  INPUT_SIZE: [8, 256, 256]
  OUTPUT_SIZE: [8, 256, 256]
  IN_PLANES: 1
  OUT_PLANES: 1
  LOSS_OPTION: [['WeightedBCE']]
  TARGET_OPT: ['0']
  WEIGHT_OPT: [['1']]
  PRE_MODEL: '/n/home12/zijzhao/outputs/unetv0_syn_baseline/volume_39999.pth'
  PRE_MODEL_ITER: 39999
DATASET:
  IMAGE_NAME: 'images/im_A+_v2_200_nocrack.h5@images/im_B+_v2_200.h5@images/im_C+_v2_200.h5'
  INPUT_PATH: '/n/home12/zijzhao/CREMI/'
  OUTPUT_PATH: '/n/pfister_lab2/Lab/zijie/outputs/unetv0_syn_baseline_encap_test'
  PAD_SIZE: [8, 64, 64]
AUGMENTOR:
  ROTATE: True
  RESCALE: True
  FLIP: True
  ELASTIC: True
  GRAYSCALE: True
  MISSINGPARTS: True
  MISSINGSECTION: True
  MISALIGNMENT: True
SOLVER:
  LR_SCHEDULER_NAME: "MultiStepLR"
  BASE_LR: 0.001
  ITERATION_STEP: 1
  ITERATION_SAVE: 5000
  ITERATION_TOTAL: 40000
INFERENCE:
  AUG_MODE: 'mean'
  AUG_NUM: 4
  OUTPUT_NAME: 'result.h5'
  STRIDE: [1, 192, 192]








